main:init destroy rbstbuyticket
init:init.c
	gcc init.c -o init -lpthread
destroy:destroy.c
	gcc destroy.c -o destroy -lpthread
rbstbuyticket:rbstbuyticket.c
	gcc rbstbuyticket.c -o rbstbuyticket -lpthread
